### ISSUE TITLE
『Feature Request』【网页快照】依然保存在Zotero默认【ITEM】文件夹中/Web page snapshots are still saved in Zotero's default ITEM folder

### ISSUE THREAD

**Issue by mtuwei** [MuiseDestiny/zotero-attanger#1]
如下图配置，以【Link】方式保存附件
Configure as shown in the figure below and save the attachment in [Link] mode
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/32591958/725f04d5-9c06-47f8-b98e-2cefdc312220)

网页剪存时，自动保存【网页快照】，并添加为【附件】
Automatically save [Web Page Snapshot] and add it as [Attachment] when cutting and saving web pages.
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/32591958/e3a3b0af-0efb-4ae7-b915-4512b6df54f4)

目前插件似乎会自动将【网页快照】以【LINK】方式移动至【目标路径】。不知能否保持【ZotFile】的特性，【网页快照】依然以【Stored Copy】方式保存在【ITEM】文件夹中，谢谢！
At present, the plugin seems to automatically move the webpage snapshot to the target path in a LINK manner. If it's possible to maintain the characteristics of ZotFile. The webpage snapshot will still be saved in the ITEM folder as a Stored Copy. Thank you!

**Comment by MuiseDestiny** [comment]
好的

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/4609ee7a-201f-4948-9d1e-22ebeeb81cc9)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-attanger/releases/tag/v1.0.2

**Comment by mtuwei** [comment]
> ![image](https://private-user-images.githubusercontent.com/51939531/293441937-1106c69b-e940-4eee-bb38-dc920498e418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5MzA2MjYsIm5iZiI6MTcwMzkzMDMyNiwicGF0aCI6Ii81MTkzOTUzMS8yOTM0NDE5MzctMTEwNmM2OWItZTk0MC00ZWVlLWJiMzgtZGM5MjA0OThlNDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDA5NTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZThiYjJjMmQ5YWJiM2VmMThlZDcxYmQ2YTUzMjRlNDI2ZmY5NTNmZWQ2ZDljNmUzNGRhZmNkZGZmMTU0NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.74diNaW6PpPrApFYhTfRg-g0rbgg2_jG3wWGCSNZP_U)

如此快速地迭代完善，十分感谢！
