### ISSUE TITLE
支持更多文件夹命名规则：杂志名称/年份/附件

### ISSUE THREAD

**Issue by llity** [MuiseDestiny/zotero-attanger#11]
{{journal}}/{{year}}  目录规则没有 journal吗？以前应该有这些规则的。
谢谢

之前支持的规则能否支持以下，重新移动附件的时候能删除原来的分类目录。
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/11771112/534d3853-44d5-4a29-aba3-fb8b13e25092)

**Comment by MuiseDestiny** [comment]
https://www.zotero.org/support/file_renaming 看这个

**Comment by MuiseDestiny** [comment]
与zotfile没太大关系，不要看zotfile文档

**Comment by llity** [comment]
谢谢，发现确实可以，有办法清理掉没有链接的目录和文件吗？

**Comment by MuiseDestiny** [comment]
> 谢谢，发现确实可以，有办法清理掉没有链接的目录和文件吗？

zotfile可以吗

**Comment by MuiseDestiny** [comment]
删除原来的分类目录 是啥意思

**Comment by llity** [comment]
> 删除原来的分类目录 是啥意思

比如我修改附件分类方法后，用 ATTANGER 移动，附件之前的目录还存在。能移动附件后删除这些空目录吗？

**Comment by MuiseDestiny** [comment]
这个不能，还是手动删除安全点。zotfile是可以的吗

**Comment by llity** [comment]
不行，手动确实安全。谢谢 :)
