### ISSUE TITLE
如何理解「文件作为『链接/副本』附加到 Zotero 条目/分类下」？

### ISSUE THREAD

**Issue by zhiyuanzhai** [MuiseDestiny/zotero-attanger#112]
如以下视频所示，即便我在设置中选择文件作为「副本」附加，插件仍然将我的文件变成了链接。
请问如何理解这一现象？

https://github.com/MuiseDestiny/zotero-attanger/assets/37478391/2e77623a-911f-42b2-9aba-db2996e25d2a

**Comment by MuiseDestiny** [comment]
你选择了副本，代表插件**不会自动**把你导入的pdf转化为链接附件。但你仍可通过右键菜单将其转换。

选择链接，那么插件就**会自动**把导入的pdf附件转化为链接附件
