### ISSUE TITLE
The problem of adding two PDF files to one item

### ISSUE THREAD

**Issue by Joseph-captain** [MuiseDestiny/zotero-attanger#120]
Hi, I came across one problem when I wanted to add another file to the existing item. Sometimes, I need to add more than one PDF files to the same item. When I using the function of automatic adding and renaming, the new added file will be set as the same filename and replace the older one. So even if I can have two attachments under this item, they actually direct to  the same file (the new one). Could you add the function of checking repeating filename and adding numbers behind the filename to distinguish files? Thanks.
我在向一个条目添加另一个附件pdf时，新添加的pdf自动重命名后，会和原有文件冲突。开发者可否修改重命名规则，自动检测已有重名文件，并在新建文件名后面添加序号进行区分？谢谢。

**Comment by MuiseDestiny** [comment]
本来就会加序号。你使用的是最新插件吗？

**Comment by Joseph-captain** [comment]
> 本来就会加序号。你使用的是最新插件吗？

你好, 我目前使用的是最新插件. 经过反复确认, 问题仍然存在. 目前情况: 如果取消自动重命名功能, 仅自动移动附件, 随后手动选择插件的重命名功能, 则可以顺利添加序号; 如果是使用插件的自动移动+自动重命名, 则会出现第二个附件顶替第一个附件的问题, 移动+命名后文件夹中只有新添加的一个文件, zotero的两个条目均链接至这一个文件, 原有文件消失.
推测是否是移动+重命名的逻辑顺序, 是先命名, 导致两个文件重名, 随后再移动, 出现重复文件名, 自动替换原有文件了?

**Comment by MuiseDestiny** [comment]
我排查一下

**Comment by MuiseDestiny** [comment]
你插件版本是多少呢

**Comment by Joseph-captain** [comment]
> 你插件版本是多少呢

开发者你好, 插件版本是1.2.3, 操作系统版本是 mac os Sonoma 14.6 Beta (windows平台上也遇到这个问题), Zotero版本是7.00-beta.91.

**Comment by MuiseDestiny** [comment]
> > 你插件版本是多少呢
> 
> 开发者你好, 插件版本是1.2.3, 操作系统版本是 mac os Sonoma 14.6 Beta (windows平台上也遇到这个问题), Zotero版本是7.00-beta.91.

1.2.4已解决此问题
