### ISSUE TITLE
1.0.5 自动抓取期刊名字时，macOS 系统中无法创建子目录

### ISSUE THREAD

**Issue by BBuniverse** [MuiseDestiny/zotero-attanger#13]
publisher 或 publicationTitle 的数据格式为 NameA/NameB，创建的文件夹直接就是 NameANameB，没有进一步创建子文件夹。

**Comment by MuiseDestiny** [comment]
截图你的子目录

**Comment by BBuniverse** [comment]
比如说用这个数据去移动文章
<img width="179" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/40508797/a79d4830-2694-4b7a-8f1c-767edfdf0ee3">
它会创建一个这种目录
<img width="177" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/40508797/0a840259-3df8-4c45-93e6-90b7e7795d20">
是否能增加一个选项，通过判断 item type 去选用不同的数据移动文章，比如有的用 publicationTitle 有的用 publisher。

**Comment by MuiseDestiny** [comment]
你的意思是假如期刊名称是”A/B“，使用`{{publicationTitle}}`作为子目录，就要创建子目录A/B，而非AB

**Comment by BBuniverse** [comment]
是的，我记得之前 zotFile 好像是能这样创建的，而且能自动判断 item type 去选择对应的数据创建目录

**Comment by MuiseDestiny** [comment]
自动判断目前应该可以做到的

https://www.zotero.org/support/file_renaming

支持类似`{{ if itemType == "book" }}{{ISBN}}{{ elseif itemType == "preprint" }}{{ DOI }}{{ elseif itemType == "journalArticle" }}{{ DOI }}{{ else }}{{ title }}{{ endif }}`语法

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/016b4cc5-8526-4de7-bcf6-849e316a6815)

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-attanger/releases/tag/v1.0.6

**Comment by BBuniverse** [comment]
子文件好像可以创建了，但是对已经存在的同名子文件夹好像没有做判断，在重复创建同名子文件夹诶

**Comment by BBuniverse** [comment]
这个移动还是会出 bug，比如之前在文件夹 A 中，我重复移动后它就会再创建一个新的文件夹 A 并移动到新的文件夹 A 里面去。

**Comment by BBuniverse** [comment]
我全部重新用插件移动一遍文件位置后，就不会再出现上述情况了
