### ISSUE TITLE
两台mac间同步后使用正常，切换到windows中无法读取同步文件夹中的附件

### ISSUE THREAD

**Issue by lungy666** [MuiseDestiny/zotero-attanger#133]
![zoteroissue](https://github.com/MuiseDestiny/zotero-attanger/assets/77978793/6c93421d-cecb-4a36-b673-16168944c28d)
使用百度网盘同步空间同步，论文附件同步文件夹中文件存在，两台mac电脑可以正常打开链接，但是切换到windows无法识别。

**Comment by SpicyRicecaker** [comment]
I find that syncing from windows -> mac works fine, but for some reason mac -> windows doesn't work. Wonder if it's a problem with CRLF on windows and LF on mac?

**Comment by lungy666** [comment]
I solved this problem by setting the root directory of the attachment correctly
![Uploading Snipaste_2024-07-09_20-23-02.png…]()

**Comment by SpicyRicecaker** [comment]
@lungy666 thanks for the info, turns out on my macos machine I had the "root directory" path set to a path generated by Google Drive, manually setting the path to where my attachments were worked!

**Comment by sora315** [comment]
你好 我想问下，你怎么设置的路径，我也是用的百度网盘，在mac和windows之间同步

**Comment by lungy666** [comment]
主要有几个点一个是设置

不同电脑要选中正确的文件夹地址

文件作为链接，然后靶路径选择正确就行
&nbsp;


林音
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月19日(星期五) 上午9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MuiseDestiny/zotero-attanger] 两台mac间同步后使用正常，切换到windows中无法读取同步文件夹中的附件 (Issue #133)














 
你好 我想问下，你怎么设置的路径，我也是用的百度网盘，在mac和windows之间同步

**Comment by lungy666** [comment]
@mialuyao 将你的链接附件根目录和你的attanger的靶路径保持一致就可以
<img width="800" alt="image" src="https://github.com/user-attachments/assets/0cc724e4-01f6-40f8-a541-1f3049de716e">
<img width="800" alt="image" src="https://github.com/user-attachments/assets/3a3f233b-781e-4047-8b96-713b9ea2e842">

**Comment by Tariya321** [comment]
如果已经经过attanger移动产生的附件link，如何修复呢？
