### ISSUE TITLE
1.0.6 zotero 7 右键条目添加附件只能选择文件夹，不显示文件

### ISSUE THREAD

**Issue by bt-njust** [MuiseDestiny/zotero-attanger#14]
如上

**Comment by MuiseDestiny** [comment]
你没有配置**源目录**所以使用`附加新文件`会让你选择文件夹

**Comment by bt-njust** [comment]
谢谢，但是配置源目录是会自动导入源目录下面的文献对吧？因为自动移动文件的好处就是在浏览器下载文件时不需要去指定文件夹，而有一些文件并不希望被自动导入（比如有些非文献类pdf）……估计众口难调吧，谢了

**Comment by MuiseDestiny** [comment]
> 配置源目录是会自动导入源目录下面的文献对吧

不会自动，是你手动点击才会导入**源目录**最新下载的pdf。

**Comment by bt-njust** [comment]
wow 谢谢
