### ISSUE TITLE
zotero自动下载的pdf,插件没有更新重命名

### ISSUE THREAD

**Issue by fredericky123** [MuiseDestiny/zotero-attanger#15]
<img width="385" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/13982749/d6aae1b2-0d37-46ad-a2c8-36b37af82d68">
如图所示，附件还是zotero自动下载时的附件名
1.0.6

**Comment by MuiseDestiny** [comment]
请给出复现步骤

**Comment by fredericky123** [comment]
https://journals.sagepub.com/doi/full/10.1509/jmr.13.0488
在这个网址下，zotero导入并自动下载PDF 然而没有被重命名

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/66970b08-cf41-4f84-8082-9e533acf2a20)

正常的，首选项请勾选自动重命名

**Comment by fredericky123** [comment]
我勾选了的，页面为英文，我再试试，不知道是不是和其他插件冲突了

**Comment by fredericky123** [comment]
刚又试了，还是没自动重命名，我的配置和插件列表如图，不知道哪里的问题
<img width="698" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/13982749/bab5294d-68ad-4ccb-bed0-bc229dcbbad8">

**Comment by fredericky123** [comment]
好奇怪，我把所有其他插件都禁用了，刚刚添加，还是没有重命名
<img width="831" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/13982749/a4a5671d-4342-4520-a48a-f55aaedff229">

**Comment by MuiseDestiny** [comment]
难道是mac独有的bug

**Comment by MuiseDestiny** [comment]
你前面的设置也发来看看呢

**Comment by fredericky123** [comment]
<img width="590" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/13982749/d28ad711-b350-4929-b74c-968d4982d706">

**Comment by MuiseDestiny** [comment]
![da77a5d88622f08e12700932a4fa29d](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/feab217a-a57e-4d32-baf2-b2e89b269163)
