### ISSUE TITLE
Rename and move doesn't work properly with linked files

### ISSUE THREAD

**Issue by kavanaram** [MuiseDestiny/zotero-attanger#154]
If attanger is set to attach links to the zotero item, and set to rename the file, it doesn't work properly. The file is renamed first as a zotero attachment, then moved into the assigned root directory and linked, but is renamed again as "PDF" in the linked file shown in zotero, rather than the filename format prescribed in zotero. 

Please let me know why this issue is arising, and if it can be corrected. 

Thanks!

**Comment by iiwenwen** [comment]
The issue of renaming and moving files with the filename "PDF" can be resolved by going to Settings - General - File Renaming - Rename linked files, and unchecking the option at the beginning of the rename linked files, which will allow normal renaming.

**Comment by cyanescent** [comment]
Thanks a lot, that very counterintuitive, but that does solve the renaming issue!

**Comment by kavanaram** [comment]
This works, thanks for the clarification :)

**Comment by zpofrp** [comment]
thank you very much.
