### ISSUE TITLE
设置页面打不开此插件的设置

### ISSUE THREAD

**Issue by sjhsbhqf** [MuiseDestiny/zotero-attanger#16]
设置页面打不开此插件的设置。重装插件，重启zotero都已经尝试

![image](https://github.com/MuiseDestiny/zotero-attanger/assets/41407099/2b969261-3101-4343-928b-cb7aa16bb4e8)

**Comment by MuiseDestiny** [comment]
请汇报你的attanger版本，以及你安装的所有插件。

**Comment by sjhsbhqf** [comment]
> 请汇报你的attanger版本，以及你安装的所有插件。

不好意思，问题没描述全面。

attanger版本是1.0.7

Better Notes for Zotero插件，版本号是1.1.4-49
Crush Reference插件，版本号是0.6.4
Easier Citation插件，版本号是0.4.2
Ethereal Style插件，版本号是3.3.3.9
Jasminum插件，版本号是1.0.0-14
Magic for Zotero插件，版本号是1.3.3.2
Translate for Zotero插件，版本号是1.1.0-beta.28
Zotero Addons插件，版本号是1.4.5
Zotero One插件，版本号是5.4.1

zotero版本是7.0.0-beta.54+6b996d4f9(64-bit)

**Comment by MuiseDestiny** [comment]
你禁用所有，除了attanger，看看正常不。然后一个个开启插件，看哪个导致的

**Comment by sjhsbhqf** [comment]
> 你禁用所有，除了attanger，看看正常不。然后一个个开启插件，看哪个导致的

![image](https://github.com/MuiseDestiny/zotero-attanger/assets/41407099/b213b63b-360d-46cd-8dfa-25764ae17ebe)

**Comment by MuiseDestiny** [comment]
稍等我修复

**Comment by sjhsbhqf** [comment]
> 稍等我修复

Thanks♪(･ω･)ﾉ

**Comment by MuiseDestiny** [comment]
稍后请更新1.0.8

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-attanger/releases/tag/v1.0.8

**Comment by sjhsbhqf** [comment]
> 稍后请更新1.0.8

![image](https://github.com/MuiseDestiny/zotero-attanger/assets/41407099/4b3e0d9f-2e84-413c-99b9-fb993a2e824f)


已解决
