### ISSUE TITLE
是否考虑添加send to tablet 的功能？

### ISSUE THREAD

**Issue by JiLisx** [MuiseDestiny/zotero-attanger#165]
可以电脑和平板端实现pdf批注的同步和更新。

**Comment by RICJMZ** [comment]
我在Ipad下载最新版的Zotero app，使用坚果云Webdav存储同步后，批注好像也会自动更新的

**Comment by JiLisx** [comment]
我是iCloud➕PDF expert，之前用tablet的推送和拉取功能非常丝滑～ 没有配置坚果云和webdav，ipad上的zotero只能看个目录
________________________________

**Comment by zzlb0224** [comment]
> Webdav

请问pdf也是通过webdav同步吗？

**Comment by zzlb0224** [comment]
> 我在Ipad下载最新版的Zotero app，使用坚果云Webdav存储同步后，批注好像也会自动更新的

@RICJMZ ,请问pdf也是使用的Webdav同步吗？

**Comment by RICJMZ** [comment]
> > 我在Ipad下载最新版的Zotero app，使用坚果云Webdav存储同步后，批注好像也会自动更新的
> 
> @RICJMZ ,请问pdf也是使用的Webdav同步吗？

是的，用坚果云同步之后，可以直接在ipad上下载pdf

**Comment by MuiseDestiny** [comment]
send to tablet是zotfile功能。attanger目的是附件管理，send to tablet不属于计划功能。但欢迎PR
