### ISSUE TITLE
坚果云的靶目录/根目录应该如何设置

### ISSUE THREAD

**Issue by wm9911** [MuiseDestiny/zotero-attanger#168]
想请问一下大佬，我是Mac，用坚果云同步，zotero attanger靶目录设置里面根目录无法通过复制坚果云地址，只能选择本地目录，应该如何操作？感谢感谢！期待回复

**Comment by rexwater** [comment]
你如果有裝堅果雲的程式，電腦裡應該會有一個它的資料夾，把目錄放在那個資料夾裡就可以了

**Comment by MuiseDestiny** [comment]
坚果云有webdav不要需要使用本插件
