### ISSUE TITLE
跨文件系统找不到文件 (从 linux 到 windows)

### ISSUE THREAD

**Issue by junyixu** [MuiseDestiny/zotero-attanger#17]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/40481594/2e6cb387-d1ca-4ed4-9737-d908c4e57c51)

以前用 zotfile 是可以正常找到的，不知还需要什么设置，这是我现在的设置:

![image](https://github.com/MuiseDestiny/zotero-attanger/assets/40481594/a3777a93-6d47-4be6-8935-b3c8c04661ad)

**Comment by MuiseDestiny** [comment]
怎么复现你的错误

**Comment by junyixu** [comment]
> 怎么复现你的错误

先在 Linux 端 move 一个文件
![IMG20240108211436](https://github.com/MuiseDestiny/zotero-attanger/assets/40481594/94c10216-c9d6-4598-b6f1-b3bc0c2a8941)

然后同步
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/40481594/4e16f2a1-e046-477d-9628-bf9ada971a2d)

最后去 windows 端同步后
再打开那个文件

**Comment by junyixu** [comment]
那个文件已经借助外部手段 (如 Syncthing, OneDrive) 同步过了，并且设置的路径也如第一个对话中所示的

**Comment by junyixu** [comment]
子目录设置的都是 `{{authors max="1" name="family-given" name-part-separator=","}}`

**Comment by junyixu** [comment]
我猜问题在于 attanger 在移动和链接的时候默认用的是绝对路径 而不是相对路径
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/40481594/587af47d-3839-4359-9a2a-d65d7723adf0)

**Comment by junyixu** [comment]
抱歉，是我 attanger 路径设置错了
