### ISSUE TITLE
1.0.8 文章高亮记录，阅读记录全部消失

### ISSUE THREAD

**Issue by BBuniverse** [MuiseDestiny/zotero-attanger#18]
我全部重新用插件移动一遍文档位置后，就不会再出现重复创建同名文件夹的情况了。但是我现在所有移动之前的文章高亮标注全部丢失，Chartero 的阅读时长也全部归零。

本地对应记录应该还是有的吧，有什么方法全部找回对应的阅读记录吗？

并且操作次数多了之后，选择按日期排序会出现顺序错误，其他列也有类似的情况。

**Comment by yzy1228682367** [comment]
出现同样的问题，zotero file仅移动而不重命名不会出现注释消失的问题，而且笔记链接仍可跳转。同问请问有什么办法找回消失的注释吗？
https://github.com/MuiseDestiny/zotero-attanger/assets/50101175/dca79f92-de20-44fd-921e-60a6b91758aa

**Comment by MuiseDestiny** [comment]
确实存在此问题，正在排查

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/840afc67-49e9-44dd-8030-50ee3a597bb8)

先这样，然后。在zotero回收站撤销删除。试试能不能恢复

**Comment by yzy1228682367** [comment]
> 先这样，然后。在zotero回收站撤销删除。试试能不能恢复
> 

这样操作以后在回收站找不到这个文件。

**Comment by MuiseDestiny** [comment]
> > 先这样，然后。在zotero恢复站取消删除。尝试不能恢复
> 
> 这样操作以后在恢复站找不到这个文件。

那先回收站撤销删除呢

**Comment by yzy1228682367** [comment]
> 
> 那先回收站撤销删除呢

回收站里面本来没有这个文件耶。

**Comment by MuiseDestiny** [comment]
> > 那先回收站撤销删除呢
> 
> 回收站里面本来没有这个文件耶。

涉及的文献多吗

**Comment by yzy1228682367** [comment]
> 
> 涉及的文献多吗

emm 还挺多的(/∇＼*)。

**Comment by MuiseDestiny** [comment]
> > 涉及的文献多吗
> 
> emm 还挺多的(/∇＼*)。

今日删除的吗

**Comment by yzy1228682367** [comment]
> 今日删除的吗

不是，过了三天了(/∇＼*)

**Comment by BBuniverse** [comment]
我的去年一整年的阅读记录都没了 孩子现在哭了

希望能找回来，再不济希望以后不再出现这个问题

**Comment by yzy1228682367** [comment]
> 希望能找回来，再不济希望以后不再出现这个问题

我也哭了(┬＿┬) 但是最新一版解决了移动注释消失的问题。

**Comment by MuiseDestiny** [comment]
30天后才会自动删除的

**Comment by MuiseDestiny** [comment]
等我写个脚本 试试能恢复不

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/0bfdd815-5bd7-462d-8d6d-39aa1c4ded8a)

https://github.com/MuiseDestiny/zotero-attanger/releases/tag/v1.0.10

下载这个，然后

![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/967843b4-5060-4ce0-9bff-6481f63a4602)

**Comment by yzy1228682367** [comment]
哇 感谢P大～好像不行(/∇＼*)

Uploading CleanShot 2024-01-08 at 20.43.46 - 01.mp4…
