### ISSUE TITLE
移动文件导致附件显示“PDF”的原因分析

### ISSUE THREAD

**Issue by iiwenwen** [MuiseDestiny/zotero-attanger#187]
**根本原因：移动文件的代码中使用了Zotero.Attachments.linkFromFile(options)函数**

<img width="678" alt="image" src="https://github.com/user-attachments/assets/8e136435-f98a-43e3-866a-ac09dc0e96a4">

**为什么要显示为"PDF"？** [详见](https://forums.zotero.org/discussion/comment/327390/#Comment_327390)
<img width="771" alt="image" src="https://github.com/user-attachments/assets/5f0bf382-e7b2-4623-843d-ddded2329768">

**如何解决？**

1. 修改Zotero.Attachments.linkFromFile(options)中的options，增加title属性，并将参数设置附件的文件名
2. 修改movieFile的代码，修改Zotero中的Zotero.Attachments.convertLinkedFileToStoredFile的方法来创建新的附件条目

建议：修改movieFile的代码，因为使用Zotero.Attachments.convertLinkedFileToStoredFile创建新附件条目的效率更高，速度更快。

**Comment by MuiseDestiny** [comment]
欢迎pr
