### ISSUE TITLE
[bug] 二次移动附件后，附件没有作为链接附件附加到条目上

### ISSUE THREAD

**Issue by zhikaiyici** [MuiseDestiny/zotero-attanger#193]
复现步骤：
1. 移动附件，附件转为链接附件。
2. 撤销移动（不勾选”储存后删除原始文件“），附件转为副本附件（此时靶目录中还存在步骤1链接的附件）。
3. 再次选择移动附件，此时由于步骤2中没有选择删除原始文件，导致本次移动附件操作不能生成附件链接，同时副本也会消失，条目成为无附件条目。

若在步骤2中勾选了”储存后删除原始文件“，则在步骤3中将正常生成附件链接，不会丢失附件。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-attanger/releases/tag/1.2.8
