### ISSUE TITLE
attanger设置打不开

### ISSUE THREAD

**Issue by horaynia** [MuiseDestiny/zotero-attanger#2]
安装后，选项里，点击attanger后右侧舞相关设置界面出现
<img width="800" alt="iShot_2023-12-30_17 51 31" src="https://github.com/MuiseDestiny/zotero-attanger/assets/50537627/3735cffa-e128-466c-b19a-b81722b3b8cb">

**Comment by MuiseDestiny** [comment]
尝试升级reference插件

**Comment by jlu511** [comment]
reference 最新的.6.4，依然不好使

**Comment by jlu511** [comment]
> 尝试升级reference插件

reference 最新的.6.4，依然不好使

**Comment by horaynia** [comment]
reference已经是最新版，但也打不开
<img width="721" alt="iShot_2023-12-31_12 30 38" src="https://github.com/MuiseDestiny/zotero-attanger/assets/50537627/779a67ce-ed83-4bb6-96dd-a7c77a87d5b3">
