### ISSUE TITLE
BUG：移动附件会导致附件丢失 功能建议：重命名并移动附件

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-attanger#20]
# BUG：移动附件会导致附件丢失 
操作：
第一步：右键条目>附件管理>重命名附件（出现下图）
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/104330036/84312b35-5419-4a13-a607-e43c2eb969da)
第二步：右键条目>附件管理>移动附件
附件丢失（因为上图中两个附件的名称是一样的）

# 功能建议：重命名并移动附件
现在只能手动去操作，希望抓取条目后能自动 重命名并移动附件 到指定文件夹

重命名附件+移动附件===>重命名并移动附件

**Comment by 1067237855** [comment]
1.1.0-b1
> 汇报插件版本

**Comment by MuiseDestiny** [comment]
> 现在只能手动去操作，希望抓取条目后能自动 重命名并移动附件 到指定文件夹

首选项勾选自动。会自动


bug没看懂，什么是`正文PDF` `支持信息PDF`

**Comment by 1067237855** [comment]
PDF原名称：AAAAA
PDF原名称：BBBBB
第一步：右键条目>附件管理>重命名附件
两个PDF均会被重命名为：CCCCC

第二步：右键条目>附件管理>移动附件
被重命名为：CCCCC的两个文件（AAAAA和BBBBB）会丢失其中一个

> bug没看懂，什么是`正文PDF` `支持信息PDF`

**Comment by MuiseDestiny** [comment]
> PDF原名称：AAAAA PDF原名称：BBBBB 第一步：右键条目>附件管理>重命名附件 两个PDF均会被重命名为：CCCCC
> 
> 第二步：右键条目>附件管理>移动附件 被重命名为：CCCCC的两个文件（AAAAA和BBBBB）会丢失其中一个
> 
> > bug没看懂，什么是`正文PDF` `支持信息PDF`

就是俩pdf，重命名应该有后缀(类似`_1`)作为区分

**Comment by 1067237855** [comment]
没有后缀(类似`_1`)作为区分，只要是多个文件，重命名的名称都一样
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/104330036/3fb75959-d5a3-4d18-8319-2373733bace1)

> 就是俩pdf，重命名应该有后缀(类似`_1`)作为区分

**Comment by MuiseDestiny** [comment]
> 没有后缀(类似`_1`)作为区分，只要是多个文件，重命名的名称都一样 ![image](https://private-user-images.githubusercontent.com/104330036/295813501-3fb75959-d5a3-4d18-8319-2373733bace1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTU0MTcsIm5iZiI6MTcwNDk1NTExNywicGF0aCI6Ii8xMDQzMzAwMzYvMjk1ODEzNTAxLTNmYjc1OTU5LWQ1YTMtNGQxOC04MzE5LTIzNzM3MzNiYWNlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwNjM4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Mzc1ZDM0YzRiZjY5ODI2NmQyZjExZDA5MTI0ZjZiN2Q5ZTc0NWM4MzQyNjhkYThlNmEwYmM4MjBjMTYxYTJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C6qTSOemjgqed1zLHAddXBEWF2Z2ofZuYKywj8QQAAo)
> 
> > 就是俩pdf，重命名应该有后缀(类似`_1`)作为区分

**应该**有，支持这个后缀就解决了
