### ISSUE TITLE
使用“查找可用的pdf”获得的附件以及网页抓取均无法自动重命名

### ISSUE THREAD

**Issue by fantab01** [MuiseDestiny/zotero-attanger#22]
### 我已勾选自动重命名设置，如图（所有插件和zotero均为最新版本；已安装插件为：awesomeGPT；reference；茉莉花；style；magic；pdf translate；attanger）
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/45958766/9c8dc0ee-82da-434e-a2bf-88582cb066b6)
### 这个不需要特定的文章来复现，我从使用这个插件至今，凡是“查找可用的pdf”功能获得的附件，均无法重命名，如下图（比如例图中显示的是全文.pdf）
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/45958766/15ea0a98-8799-4856-9882-39ead29cc6bd)
### 此外，我个人在使用时，凡是网页抓取的文章，附件也均无法重命名，如下图（期刊例子：https://link.springer.com/article/10.1007/s40864-019-00110-6）
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/45958766/225c96af-9ede-41b0-94bc-1af1ca7d0148)
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/45958766/b0048625-d263-4f0f-92e0-16185232433c)
### 还有一个疑问顺便请教，无论我勾选自动移动添加的附件与否，貌似对网页抓取或者“查找可用的pdf”功能获得的附件位置没有任何影响，我不太理解这个功能到底要实现什么效果。我也看过作者您在b站的教学，也没有提及相关内容。

**Comment by pengxy0** [comment]
这个功能可以手动命名，感觉在下载文献的时候，可以分清楚，哪个是正文哪个是支撑信息。不知道大老师是不是出于这方面的考虑。
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/130196652/3cb5ba9f-f3e1-40a5-9b0d-3a651c3c6d9e)
