### ISSUE TITLE
移动附件bug

### ISSUE THREAD

**Issue by cgl-sd** [MuiseDestiny/zotero-attanger#23]
感谢作者开发的插件，能够在zotero7中更好的管理文件，我在使用时发现了如下问题：
当我选中一个文件目录中所有的文献并进行移动文件时不会发生问题，
当我选中所有的文献进行移动时就会发生bug，文献移动后的windows目录位置不是其在zotero目录中的位置。

**Comment by MuiseDestiny** [comment]
请提供你的插件设置。
