### ISSUE TITLE
Name suggestion to avoid trademark conflicts

### ISSUE THREAD

**Issue by munael** [MuiseDestiny/zotero-attanger#24]
Hello o/

I've seen on the forums that you were asked to change the name of an earlier plugin "zotero-file" because of the word zotero in the name.

If this plugin is the intended successor to zotfile, it would make sense to name it similarly and avoid conflicts.

For example: `zot-attanger` or 	`zot-file-2` or `zot-file-7` or `zot-file-neo`, and so on.

Best of luck. Looking forward to a full English localization (docs, ...) 😄

**Comment by MuiseDestiny** [comment]
English doc will be written latter.
