### ISSUE TITLE
annotation注释在移动并重命名附件之后消失

### ISSUE THREAD

**Issue by sjhsbhqf** [MuiseDestiny/zotero-attanger#25]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/41407099/948ef17c-cb17-4019-bd26-2d02ebee15d6)

因为之前没用这个插件用链接PDF的方式管理附件，所以在做注释（annotations）之后进行的移动并重命名。

而当我移动之后，再打开这个item的PDF，所有的注释消失不见了。

![image](https://github.com/MuiseDestiny/zotero-attanger/assets/41407099/59b48bb6-870c-48ec-acf0-f09ed1d4c03b)

请问这个问题如何解决和防范呢？？

**Comment by MuiseDestiny** [comment]
最新版已经解决了这个问题。你的插件太旧。
