### ISSUE TITLE
导入pdf后，如果没有成功索引到元数据，则无法实现正确的移动。

### ISSUE THREAD

**Issue by reoLantern** [MuiseDestiny/zotero-attanger#26]
将一份pdf拖入zotero，但zotero没有获取到这个文件正确的元数据。此时，attanger没有自动进行移动和重命名。右键文件->attanger->移动附件，pdf会被正确移动到靶路径，但是zotero没有得到新移动的文件目录，再次双击pdf，会提示文件已经被移动不存在。

**Comment by MuiseDestiny** [comment]
纯pdf（无元数据）不应该提供菜单按钮。下个版本会修复

**Comment by reoLantern** [comment]
> 纯pdf（无元数据）不应该提供菜单按钮。下个版本会修复

您好，您的意思是纯pdf不会被attanger进行文件管理吗，还是不会重命名？感觉还是需要把纯pdf移动位置的，不过不需要重命名。感谢
