### ISSUE TITLE
Rename Issue - Suffix Reset

### ISSUE THREAD

**Issue by TheLight8** [MuiseDestiny/zotero-attanger#27]
Hello!
Simple issue: when I "Move PDF", if a file is already in the folder, the extension adds a suffix.
What I'd like to happen: in case one of the file is removed, if I "Rename PDF" the suffix is removed.
Amazing extension, thank you for your work!

**Comment by MuiseDestiny** [comment]
Actually, deleting an Zotero Attachment Item does not remove the attachment file (that has been moved to the target path). Moreover, detecting the event of a file being deleted in the system is challenging for the extension.
