### ISSUE TITLE
多设备靶路径不同，能否实现同步

### ISSUE THREAD

**Issue by reoLantern** [MuiseDestiny/zotero-attanger#28]
attanger的作用是自动为附件替换一个文件链接，指向OneDrive下指定的文件夹。但是当多个设备的OneDrive路径不同时，是否还能实现顺畅的同步呢？
感觉可以在attanger的打开功能里，设置为从该设备设置好的靶路径打开相应的文件，不知作者有没有兴趣实现。

**Comment by reoLantern** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/61400197/e10eebaa-829e-4cff-8bdd-82c234a25cbd)
如图是发生的错误，因为之前的A电脑OneDrive在C盘，所以文件链接在C盘下，但是这台B电脑的OneDrive在D盘。我已经在B电脑设置了靶路径为D盘OneDrive的相应文件夹，但是依然无法正确找到文件。

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/6295e7cb-7fa5-4468-9698-312aa3d064cd)
