### ISSUE TITLE
添加新文件时，重命名的Bug

### ISSUE THREAD

**Issue by ChenglongMa** [MuiseDestiny/zotero-attanger#29]
你好，

非常感谢作者开发的插件，对Zotero 7支持非常好。
不过有几个小问题想报告一下：

1. 当我引入新的条目时，重命名会提示文件已存在并自动添加后缀名，如下图：
   
![Snipaste_2024-01-19_16-51-26](https://github.com/MuiseDestiny/zotero-attanger/assets/33501679/8f75e141-cdcc-47e8-97cf-4170d59e28fe)
   但是我的文件夹中没有重复的文件
2. 另外，当我右键点击重命名文件或移动文件时，若目标文件被占用（比如在其他程序中被打开），该插件会卡住，并不断提示上述 Progress Window，查看日志发现：
   
![Snipaste_2024-01-19_16-52-53](https://github.com/MuiseDestiny/zotero-attanger/assets/33501679/e476b49c-c1c4-4e1d-9f55-d4f5b56dbb9b)

如果不嫌弃我可以尝试修复该bug。

谢谢！

**Comment by hhowardwang** [comment]
同样遇到重命名的问题，通过右键菜单重命名后，可以看到实际文件名已经改变，但是 zotero 中预览的没有改变，以顾老师等的文章为例：

下图为实际文件名
<img width="331" alt="PixPin_2024-01-23_16-49-36" src="https://github.com/MuiseDestiny/zotero-attanger/assets/126569075/4fa9d845-e02a-4bcf-bdec-a2b769d089a8">

下图为条目下文件名
<img width="752" alt="PixPin_2024-01-23_16-49-28" src="https://github.com/MuiseDestiny/zotero-attanger/assets/126569075/c2f290e0-3d9a-47be-b4f8-d159ae12abd6">

希望作者可以看一下，谢谢！

**Comment by MuiseDestiny** [comment]
> 希望作者可以看一下，谢谢！

这个不属于bug，zo的设定。文件名是文件名，pdf条目标题是条目标题。

**Comment by hhowardwang** [comment]
> > 希望作者可以看一下，谢谢！
> 
> 这个不属于bug，zo的设定。文件名是文件名，pdf条目标题是条目标题。

我指的是条目下的文件名 Full Text PDF 啦，在zotero6中用zotfile更改文件名后，条目下的文件名也会改的来着，请问作者大大可以实现这个吗，谢谢。

**Comment by MuiseDestiny** [comment]
欢迎pr，然后`renamefile function是来自zotero官方代码`已经更改，修改附件条目标题。先关闭issue。

**Comment by ChenglongMa** [comment]
> 欢迎pr，然后`renamefile function是来自zotero官方代码`已经更改，修改附件条目标题。先关闭issue。

好的，我会参考官方的代码。现在正在调试，过几天提交PR。谢谢！
