### ISSUE TITLE
作者大大，用茉莉花插件抓取的条目的pdf没有自动重命名

### ISSUE THREAD

**Issue by Alfredhongs** [MuiseDestiny/zotero-attanger#3]
从知网抓取的条目，zotero内显示的还是full text pdf，且用使用了右键菜单-附件管理-附件重命名，还是没有反应，所以感觉目前抓取的知网条目那些，pdf都实现不了自动重命名

**Comment by northword** [comment]
区分附件名和文件名，参阅 zotero 官方文档 “file renaming” 小节

**Comment by MuiseDestiny** [comment]
可能需要茉莉花插件自己调用下重命名

**Comment by kabuda2077** [comment]
我也是，请问你解决了吗
