### ISSUE TITLE
重复创建同名文件夹

### ISSUE THREAD

**Issue by BBuniverse** [MuiseDestiny/zotero-attanger#30]
选择 move attachment 移动 PDF 的时候，还是没有检查本地是否已经存在同名文件夹。之前为了解决这个问题，我全部重新移动了一次，就导致丢失了所有的标注记录和阅读时长记录。
<img width="97" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/40508797/8ddeebfa-8de4-47cf-a607-106b14bdfa8e">

**Comment by Hanawa-Kazuhiko** [comment]
我也是发现这个问题了，BUG真的好多，希望作者后续能把重复文件夹合并一下。。我现在全是重复文件夹

**Comment by MuiseDestiny** [comment]
mac支持重复文件名吗

**Comment by BBuniverse** [comment]
理论上不支持
<img width="238" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/40508797/fb51e567-8111-4a5a-9523-2e5b2db2913b">

**Comment by MuiseDestiny** [comment]
好的待会发新版本试试

**Comment by BBuniverse** [comment]
我刚装上之后每次打开 Zotero 都是直接进入的 safe mode，然后网上找了教程关闭，之后软件就一直卡死无法运行了
<img width="570" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/40508797/be65a52b-2165-455e-a516-399d7fff937e">

**Comment by MuiseDestiny** [comment]
ctrl+q退出后，再打开zo

**Comment by BBuniverse** [comment]
<img width="84" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/40508797/7de469f7-1f2c-4b7a-a4e3-e890bfd29c0a">
移动创建重复文件夹的问题还是存在

**Comment by BBuniverse** [comment]
找到 bug 了，新文件夹可能是后面带了一个空格，也就是说下面的代码里面不能有空格，不然创建的文件夹会最后面自带一个空格

```
{{if itemType=="preprint"}}{{repository}}{{elseif itemType=="journalArticle"}}{{publicationTitle}}{{elseif itemType=="conferencePaper"}}{{publisher}}{{endif}}
```
