### ISSUE TITLE
学位论文会被移动到C盘根目录，无法移动到指定目录

### ISSUE THREAD

**Issue by Hanawa-Kazuhiko** [MuiseDestiny/zotero-attanger#31]
子目录设置是 {{publicationTitle}}/{{year}}
移动后学位论文按照以前的zotfile会创建一个学校名字的子文件夹，然后是年份的子文件夹。但是这个插件会移动到根目录而不是指定目录，并且只有年份的子文件夹，怎么解决？
![微信截图_20240124223906](https://github.com/MuiseDestiny/zotero-attanger/assets/41327633/a935e955-e57f-484c-b1f2-b99d3f5a7bfd)
![微信截图_20240124223826](https://github.com/MuiseDestiny/zotero-attanger/assets/41327633/fe00189b-6f4b-48df-8d60-133938362387)

**Comment by MuiseDestiny** [comment]
是否设置了靶路径，请截图你的首选项

**Comment by Hanawa-Kazuhiko** [comment]
> 是否设置了靶路径，请截图你的首选项

设置了的，期刊论文基本都没问题，学位论文和部分会议论文就会被移动到C盘根目录，而不是我设置的云盘路径。
![微信截图_20240125102800](https://github.com/MuiseDestiny/zotero-attanger/assets/41327633/2a46b1b0-a479-4f84-9f2b-4866a278d0a4)
![微信截图_20240125102815](https://github.com/MuiseDestiny/zotero-attanger/assets/41327633/8165251a-dbb5-409a-90e4-ea4c0fe73dd8)

**Comment by MuiseDestiny** [comment]
> 设置了的，期刊论文基本都没问题，学位论文和部分会议论文就会被移动到C盘根目录，而不是我设置的云盘路径。

publicationTitle是期刊名称。学位论文没有期刊名称这属于正常现象，建议设置if判断，如果是学位论文则用学校，而不是publicationTitle，见https://www.zotero.org/support/file_renaming

**Comment by MuiseDestiny** [comment]
比如，下面是官方的例子

`{{ if itemType == "book" }}{{ISBN}}{{ elseif itemType == "preprint" }}{{ DOI }}{{ elseif itemType == "journalArticle" }}{{ DOI }}{{ else }}{{ title }}{{ endif }}`

**Comment by Hanawa-Kazuhiko** [comment]
> 比如，下面是官方的例子
> 
> `{{ if itemType == "book" }}{{ISBN}}{{ elseif itemType == "preprint" }}{{ DOI }}{{ elseif itemType == "journalArticle" }}{{ DOI }}{{ else }}{{ title }}{{ endif }}`

是这样写的吗？
{{ if itemType == "book" }}{{publisher}}{{ elseif itemType == "thesisType" }}{{ university }}{{ elseif itemType == "journalArticle" }}{{publicationTitle}}{{else}}{{Others}}/{{year}}
弄完还是没有用，而且也不止学位论文有这个问题，还有很多其他类型的报告，会议，预印等等。至少能像以前一样默认能移动到我设置的文件夹吧，而不是C盘根目录。。。
