### ISSUE TITLE
直接进入的 safe mode

### ISSUE THREAD

**Issue by BBuniverse** [MuiseDestiny/zotero-attanger#34]
我刚装上之后每次打开 Zotero 都是直接进入的 safe mode，然后网上找了教程关闭，之后软件就一直卡死无法运行了
<img width="570" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/40508797/be65a52b-2165-455e-a516-399d7fff937e">
现在重装覆盖了软件，解决了卡死的问题，但是依然还是会直接进入 safe mode

_Originally posted by @BBuniverse in https://github.com/MuiseDestiny/zotero-attanger/issues/30#issuecomment-1909256174_

**Comment by MuiseDestiny** [comment]
ctrl q

**Comment by BBuniverse** [comment]
command q 能退出 safe mode了，但是重启后依然会卡死

**Comment by MuiseDestiny** [comment]
> command q 能退出 safe mode了，但是重启后依然会卡死

进入安全模式，禁用所有插件 再逐个开启

**Comment by BBuniverse** [comment]
查到是 Chartero 的问题，把它升级到 2.3.3 就 ok 了
