### ISSUE TITLE
关于“等”和"et al"的重命名，结果和zotfile不一致

### ISSUE THREAD

**Issue by baker221** [MuiseDestiny/zotero-attanger#38]
rt，下面两个是之前zotfile的结果，上面的是zotero-attanger的结果。目前测试是需要把zotero语言改成英文才能生效。

<img width="426" alt="Snipaste_2024-01-30_18-04-04" src="https://github.com/MuiseDestiny/zotero-attanger/assets/43471538/fcae2f2a-abc0-489a-a9c2-b1cddf71c3f7">

**Comment by crazyi** [comment]
> > 这个跟插件没关系，是你自己设置重命名的规则问题
> 
> 但是zotfile的重命名规则就能够用et al，zotero里设置的就只有中文

新插件没有重命名的功能，默认就是引用zotero自带的重命名方案，你想要用et al或者等就自己根据文献语言加判断语句添加suffix，官网就有教程

**Comment by crazyi** [comment]
`{{if firstCreator == authors}}{{authors  max = "1"}}{{elseif language == "en-US"}}{{authors max = "1" suffix=" et al."}}{{elseif language == "en"}}{{authors max = "1" suffix=" et al."}}{{elseif language == "us"}}{{authors max = "1" suffix=" et al."}}{{elseif language == "zh-CN"}}{{authors max = "1" suffix="等"}}{{elseif language == "zh"}}{{authors max = "1" suffix="等"}}{{elseif language == "cn"}}{{authors max = "1" suffix="等"}}{{endif}}_{{year}}_{{title truncate = "100"}}`
送你一个自用的重命名规则，根据语言字段自适应等或et al.，单作者不加等或et al.，作者多于等于2个的时候加等或et al.

**Comment by harvein1234** [comment]
> > `{{if firstCreator == authors}}{{authors max = "1"}}{{elseif language == "en-US"}}{{authors max = "1" suffix=" et al."}}{{elseif language == "en"}}{{authors max = "1" suffix=" et al."}}{{elseif language == "us"}}{{authors max = "1" suffix=" et al."}}{{elseif language == "zh-CN"}}{{authors max = "1" suffix="等"}}{{elseif language == "zh"}}{{authors max = "1" suffix="等"}}{{elseif language == "cn"}}{{authors max = "1" suffix="等"}}{{endif}}_{{year}}_{{title truncate = "100"}}` 送你一个自用的重命名规则，根据语言字段自适应等或et al.，单作者不加等或et al.，作者多于等于2个的时候加等或et al.
> 
> 两个作者之间一般加和，我自己编了一条，请大家指正： {{if {{authors join="和" }} == {{firstCreator}} }}{{ if language == "zh-CN" }}{{ authors join = "和"}}{{ elseif language == "zh" }}{{ authors join = "和"}}{{ elseif language == "cn" }}{{ authors join = "和" }}{{ else }} {{ authors join = " and "}}{{ endif }} {{ else }} {{ if language == "zh-CN" }}{{ authors max = "1" suffix="等"}}{{ elseif language == "zh" }}{{ authors max = "1" suffix="等"}}{{ elseif language == "cn" }}{{ authors max = "1" suffix="等"}}{{ else }} {{authors max = "1" suffix=" et al."}}{{endif}}{{endif}}_{{ year }}_{{ title truncate = "91" }}

文件名前会莫名其妙多一个空格
