### ISSUE TITLE
P大，批量重命名的时候会出现有的文档因为找不到检索不到原文件无法重命名，而导致其后的所有文件都不再重命名，可否出现此种情况时，zotero发出通知告知。

### ISSUE THREAD

**Issue by yzy1228682367** [MuiseDestiny/zotero-attanger#4]

**Comment by yzy1228682367** [comment]
P大，检索不到原文件的时候，似乎还是没有发出通知

https://github.com/MuiseDestiny/zotero-attanger/assets/50101175/f3d3b51e-4f26-4917-ab65-c9ac353b8c75

**Comment by MuiseDestiny** [comment]
pdf不存在就是没通知的

**Comment by yzy1228682367** [comment]
> pdf不存在就是没通知的

好哩，谢谢P大
