### ISSUE TITLE
链接类型的pdf文件无法恢复为本地类型的pdf导致ipad端无法下载pdf

### ISSUE THREAD

**Issue by Mang30** [MuiseDestiny/zotero-attanger#44]
您好，这插件使用体验很不错，但是存在一个问题，通过attanger云备份pdf后，pdf变为链接状态，如下图所示：
![微信截图_20240221155518](https://github.com/MuiseDestiny/zotero-attanger/assets/77732467/146aafed-85b2-4514-936a-e96abdef6e5d)

但在此之后，ipad端的zotero无法下载pdf文件了，ipad段报错显示如下：
![微信截图_20240221155959](https://github.com/MuiseDestiny/zotero-attanger/assets/77732467/4de03207-85d6-439f-b9b1-eef5b11d1252)

于是我想将链接类型的pdf文件恢复为本地类型的pdf，即让它（pdf）回到zo初始位置，但无法成功实现。相关设置如下图所示：
![微信截图_20240221155418](https://github.com/MuiseDestiny/zotero-attanger/assets/77732467/634a4924-e161-4bbe-bd29-7903393dda1f)
![微信截图_20240221155403](https://github.com/MuiseDestiny/zotero-attanger/assets/77732467/4c4037a1-f1e7-4efe-b3c2-da4cc1db75e4)

我想询问一下，是我的设置有问题，还是插件存在相关问题呢？

**Comment by crazyi** [comment]
工具->管理附件->转换已链接文件为已存储文件

**Comment by Mang30** [comment]
> 工具->管理附件->转换已链接文件为已存储文件

十分感谢🙏
