### ISSUE TITLE
建议Attach Type为link时，弹出的进度条PDF图标为链接的那个。

### ISSUE THREAD

**Issue by redleafnew** [MuiseDestiny/zotero-attanger#5]
当
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/22135631/130e1a9d-4606-4d96-99ac-67385ebb30a0)

![image](https://github.com/MuiseDestiny/zotero-attanger/assets/22135631/756b10ae-f140-4a52-be74-0db754077c80)中的图标
改为
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/22135631/b370f7ce-5334-48c8-b65a-534b0e717241)

感谢开发的插件。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-attanger/releases/tag/v1.0.3
