### ISSUE TITLE
attach new file能否设置一个快捷键

### ISSUE THREAD

**Issue by fredericky123** [MuiseDestiny/zotero-attanger#66]
比如mac下设置为ctrl +A(ttachment)

**Comment by TomBener** [comment]
+1 同需要这个功能

**Comment by MuiseDestiny** [comment]
正在增加中...

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/51939531/b9c9c03c-e04b-4f2a-b356-ec90d9697a6b)

**Comment by TomBener** [comment]
非常感谢！

可不可以给 `Rename Attachment` 和 `Move Attachment` 这两个功能分别添加一个快捷键啊？

**Comment by kitaev-chen** [comment]
> 非常感谢！
> 
> 可不可以给 `Rename Attachment` 和 `Move Attachment` 这两个功能分别添加一个快捷键啊？

 这个确实需要，以前ctrl+alt+shit一键移动并重命名，现在还要点半天。
