### ISSUE TITLE
# 快速打开

### ISSUE THREAD

**Issue by 1067237855** [MuiseDestiny/zotero-attanger#7]
# 快速open with本地附件
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/104330036/c42cc175-a00c-4787-969e-245c28175492)

# 以"标签"重命名附件
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/104330036/bf5c1c53-d2b6-4bfa-8dc4-50c72f6904af)
设置标签存放位置：“archiveLocation存档位置“
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/104330036/c5e8332d-0c78-4794-960b-7d42b2167daf)
目的：快速定位打开云盘附件
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/104330036/e825fcf9-e964-44fe-a0c6-7b5ffb4fd7f6)

**Comment by MuiseDestiny** [comment]
#标签 有更好的解决办法。无需占用zotero其他字段。

**Comment by 1067237855** [comment]
> #标签 有更好的解决办法。无需占用zotero其他字段。

求教大佬方法🙏🙏🙏我之前一直用的这个办法，添加#标签 后，青 柠的插件会 自动（以#标签）重命名附件 并 移动附件

**Comment by MuiseDestiny** [comment]
#标签 需要attanger插件更新支持。pdf阅读器选择打开其它pdf阅读器重新打开 的用处是什么

**Comment by 1067237855** [comment]
pdf阅读器选择打开其它pdf阅读器重新打开 的用处是什么

 快速（用其他PDF阅读器）open with本地附件目的（我个人常用的一些如下）：
1.借助ewbing、UPDF、小绿鲸等PDF阅读器进行AI辅助阅读（最常用）
2.借助PDFXEdit、FoxitPDFEditor、Acrobat等PDF阅读器进行⭐⭐⭐添加目录/书签（常用）⭐⭐⭐、处理图片、编辑PDF等操作

下面这个建议的意思是：在zotero的“PDF阅读界面”加一个open with按钮，而不是跳转回“条目界面”右键open with，目的在于减少切换操作，这个建议只是个很小的方便用户使用的小调整
> # 快速open with本地附件
> ![image](https://private-user-images.githubusercontent.com/104330036/293616414-c42cc175-a00c-4787-969e-245c28175492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxOTkxMjUsIm5iZiI6MTcwNDE5ODgyNSwicGF0aCI6Ii8xMDQzMzAwMzYvMjkzNjE2NDE0LWM0MmNjMTc1LWEwMGMtNDc4Ny05NjllLTI0NWMyODE3NTQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxMjMzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YWVlZjIzNTgzYjBhMjY3ZDgyZWViZWFmNjQyYWU4Njg2NmZhNWNhZjViZjE3MGVmYTYwNDgwYWRhMGU4Nzc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KgsxdGwsmBrddGNUxxm1woZ43cENkm7rhV5KcG37mOw)

**Comment by MuiseDestiny** [comment]
快速打开：https://github.com/windingwind/zotero-actions-tags/discussions/132

**Comment by 1067237855** [comment]
大佬会添加该功能吗？
> #标签 有更好的解决办法。无需占用zotero其他字段。

**Comment by 1067237855** [comment]
主要目的是在这个地方加个按钮😂
![](https://private-user-images.githubusercontent.com/104330036/293616414-c42cc175-a00c-4787-969e-245c28175492.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NjU1NTMsIm5iZiI6MTcwNDg2NTI1MywicGF0aCI6Ii8xMDQzMzAwMzYvMjkzNjE2NDE0LWM0MmNjMTc1LWEwMGMtNDc4Ny05NjllLTI0NWMyODE3NTQ5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMFQwNTQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzYxMGY4ZjM1OTQ1MzE2ZTE3ZjA4ZDJhOWUxZjE4NGI3ZjBmNWY4YzQ0NDExNTkxOTU5NzYyMWUzMGI4NzgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WsiWtG0Q7FYP9APL46B_V61THTeZBYmAZ0A9v2NK7go)

> 快速打开：[windingwind/zotero-actions-tags#132](https://github.com/windingwind/zotero-actions-tags/discussions/132)
