### ISSUE TITLE
BUG：无法重命名和移动文件，设置面板路径选择按钮失效

### ISSUE THREAD

**Issue by shrrr** [MuiseDestiny/zotero-attanger#78]
* 今天升级zotero到7.0.0-beta.71+03d0ea436 (64-bit)版本，出现了zotero-attanger无法重命名和移动文件的情况
* 重新安装最新版插件后，发现依然无法重命名和移动文件，甚至插件设置面板里面的路径选择按钮也出现了失效的情况
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/39425276/85dc2f0e-7452-40e4-87f3-6d28861f4f2c) 
即点击图中的目录选择按钮没有响应

**Comment by reoLantern** [comment]
确实，也无法选择根目录了

**Comment by wangtongxue521** [comment]
我这里也是无法选择源径和靶路径

**Comment by xy9485** [comment]
我也遇到了相同问题，zotero更新到最新版本：7.0.0-beta.72+128a540af

**Comment by Tabshhh** [comment]
我也是相同的问题

**Comment by MuiseDestiny** [comment]
已修复

**Comment by shrrr** [comment]
> 已修复

好嘞，感谢，辛苦了
