### ISSUE TITLE
Attanger配置Bug，求助

### ISSUE THREAD

**Issue by DrVelsharoom** [MuiseDestiny/zotero-attanger#79]
运行设备：M3 Pro Macbook Pro
运行环境：Mac OS 14.5 Beta（23F5049f）
软件环境：Zotero 7.0.0-beta.70+d654daae2
插件版本：1.1.6
BUG描述：1.插件设置中源路径和靶路径无法选择，无法更改。
                   2.“附加新文件”功能无法使用
<img width="615" alt="截屏2024-04-10 00 45 10" src="https://github.com/MuiseDestiny/zotero-attanger/assets/117026863/90677aaa-d3e8-4429-bbd8-784807517284">
PS：望拨冗回复

**Comment by rhcdc** [comment]
Windows10 同样问题

**Comment by reoLantern** [comment]
同样问题，更新zotero新版本之后出现

**Comment by MuiseDestiny** [comment]
正在修复...

**Comment by MuiseDestiny** [comment]
已修复
