### ISSUE TITLE
能否设置自动移动附件，即先将文件复制到目标文件夹，再从源文件删除

### ISSUE THREAD

**Issue by fredericky123** [MuiseDestiny/zotero-attanger#8]
能否设置自动移动附件，即先将文件复制到目标文件夹，再从源文件删除
感谢！

**Comment by MuiseDestiny** [comment]
现在不是这样吗

**Comment by fredericky123** [comment]
> 现在不是这样吗

现在只是复制到目标文件夹，源文件夹里的附件不会删除

**Comment by fredericky123** [comment]
这是我的配置
<img width="597" alt="image" src="https://github.com/MuiseDestiny/zotero-attanger/assets/13982749/b1c4bf9f-d207-4e98-ab21-61ded675c527">

**Comment by MuiseDestiny** [comment]
> 现在只是复制到目标文件夹，源文件夹里的附件不会删除

OK

**Comment by fredericky123** [comment]
感谢！
