### ISSUE TITLE
beta 74中attanger中自动移动附件以及手动移动附件功能失效。

### ISSUE THREAD

**Issue by yzy1228682367** [MuiseDestiny/zotero-attanger#89]
https://github.com/MuiseDestiny/zotero-attanger/assets/50101175/bfb1b8b4-83e6-49d1-8e22-21567ea261c3

**Comment by MuiseDestiny** [comment]
首选项设置 请截图

**Comment by yzy1228682367** [comment]
![CleanShot 2024-04-16 at 13 48 18@2x](https://github.com/MuiseDestiny/zotero-attanger/assets/50101175/3f1524cf-cbe3-4b9b-b845-689a3f1c308c)
是这样子的，原本是可以的，但是更新之后不行了/苦涩

**Comment by Singal0927** [comment]
我也是

**Comment by MuiseDestiny** [comment]
你的源目录，不对。应该是下载目录。子目录貌似写的也不对吧

**Comment by MuiseDestiny** [comment]
你可以移动以下然后看下控制台报错

**Comment by MuiseDestiny** [comment]
你这个不对，你这个可以作为文件名，作为子目录不合适吧，建议用`{{collection}}`

**Comment by yzy1228682367** [comment]
(4)(+0000005): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [43410, 'https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFD2006&filename=LAWS200606003']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [43410, 'https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFD2006&filename=LAWS200606003']

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [43410, 'https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFD2006&filename=LAWS200606003']

(3)(+0000022): [Jasminum] **Jasminum selected item length: 1

(3)(+0000000): [Jasminum] show menu: search false name true boomark false

(3)(+0001182): [Jasminum] **Jasminum selected item length: 1

(3)(+0000000): [Jasminum] show menu: search false name true boomark false

(3)(+0001112): [Jasminum] **Jasminum selected item length: 1

(3)(+0000000): [Jasminum] show menu: search false name true boomark false

(3)(+0001060): [Jasminum] **Jasminum selected item length: 1

(3)(+0000000): [Jasminum] show menu: search false name true boomark false

(3)(+0001297): [Zotero Attanger] {{ if itemType == "book" }}{{ authors suffix="_" }}{{ editors suffix="编_" }}{{ title truncate="100" }}{{ publisher prefix= "_"}}{{ year prefix="_" suffix="年版"}}{{ edition prefix="（第" suffix="版)"}}{{ volume prefix="（第" suffix="卷)"}}{{ elseif itemType == "journalArticle" }}{{ authors suffix="_" }}{{ title truncate="100" }}{{ publicationTitle prefix="_" }}{{ year prefix="_" suffix="年"}}{{ issue prefix="第" suffix="期" }}{{ elseif itemType == "newspaperArticle" }}{{ authors suffix="_" }}{{ title truncate="100" }}{{ publicationTitle prefix="_" }}{{ date truncate="10" prefix="_"}}{{ elseif itemType == "case" }}{{ court suffix="_" }}{{ docketNumber }}{{ title truncate="100" prefix="_"}}{{ elseif itemType == "standard" }}{{ authors suffix="_" }}{{ title truncate="100"}}{{ publicLawNumber prefix="_" }}{{ number prefix="_" }}{{ elseif itemType == "Statute" }}{{ title truncate="100"}}{{ publicLawNumber prefix="_" }}{{ date truncate="10" prefix="_"}}{{ elseif itemType == "Thesis" }}{{ authors suffix="_" }}{{ title truncate="100"}}{{ university prefix="_" }}{{ year suffix="年" }}{{ type suffix="论文" }}{{ elseif itemType == "webpage" }}{{ authors suffix="_" }}{{ title truncate="100"}}{{ websiteTitle prefix="_网页“" suffix="”"}}{{ date truncate="10" prefix="_"}}{{ elseif itemType == "blogpost" }}{{ authors suffix="_" }}{{ title truncate="100"}}{{ blogTitle prefix="_" }}{{ websiteTitle }}{{ date truncate="11" prefix="_"}}{{ else }}{{ authors suffix="_" }}{{ year }}{{ title truncate="100" prefix="_"}}{{ endif }}

(3)(+0000008): [Zotero Attanger] subfolder 王保树_从法条的公司法到实践的公司法_法学研究_2006年第6期

(3)(+0000002): [Zotero Attanger] {}

(3)(+0005827): Running /usr/bin/sw_vers '-productVersion'

**Comment by llity** [comment]
确实不行了

**Comment by MuiseDestiny** [comment]
忘了问 你插件版本多少，最新：1.1.7

**Comment by yzy1228682367** [comment]
> 忘了问 你插件版本多少，最新：1.1.7
是1.1.7的
![CleanShot 2024-04-17 at 12 51 43@2x](https://github.com/MuiseDestiny/zotero-attanger/assets/50101175/b5eed27e-29a8-4734-bf81-6f4e5e01dcfe)

**Comment by yzy1228682367** [comment]
> 你这个子目录不对，这么写可以作为文件名，作为子目录不合适吧，建议用`{{collection}}`

因为有的文章会在不同集合里出现，而且有的时候可能会改集合的位置和名称，所以不太想用collection/苦涩

**Comment by Liurukun** [comment]
> > 你这个子目录不对，这么写可以作为文件名，作为子目录不合适吧，建议用`{{collection}}`
> 
> 因为有的文章会在不同集合里出现，而且有的时候可能会改集合的位置和名称，所以不太想用collection/苦涩

实测win下没任何问题，但是mac完全一样的设置就只能重命名不能移动！！

有没有可能 斜杠符号/的问题

**Comment by yzy1228682367** [comment]
> 有没有可能 斜杠符号/的问题

![CleanShot 2024-04-17 at 20 19 01@2x](https://github.com/MuiseDestiny/zotero-attanger/assets/50101175/7c6201a3-c544-45f3-bb5d-3c05e04f84e2)
去掉这个选项以后仍然不能移动文档(/∇＼*)

**Comment by oushiei120** [comment]
mac 不行了。所有版本都失效

**Comment by SakuraToErii** [comment]
mac 版确实不行了

**Comment by oushiei120** [comment]
谢谢！！可以了

**Comment by yzy1228682367** [comment]
> 2. 尝试自己编译最新代码，如果问题解决了，说明是Release包传错了。我在Mac上从最新源码编译的版本似乎是没问题的，需要的可以试试：[zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15036599/zotero-attanger.xpi.zip)

大佬，请问移动以后笔记中的注释跳转不回去了是正常的吗/苦涩

**Comment by oushiei120** [comment]
> Release中的版本确实不行，有可能是（1）Release包放错了，或者（2）编译环境问题。
> 
> 如果遇到移动失效的问题，可以做以下两种尝试：
> 
> 1. 将子目录规则设置为`{{ year }}`这种不包含`/`的形式，如果这种情况下可以移动，那么大概率是`menu.ts`中544行的`PathUtils.join`没有被成功修改为`PathUtils.joinRelative`。
> 2. 尝试自己编译最新代码，如果问题解决了，说明是Release包传错了。我在Mac上从最新源码编译的版本似乎是没问题的，需要的可以试试：[zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15036599/zotero-attanger.xpi.zip)
用了大佬的文件，可以移动了一下，之后立马就不行了

**Comment by oushiei120** [comment]
> Release中的版本确实不行，有可能是（1）Release包放错了，或者（2）编译环境问题。
> 
> 如果遇到移动失效的问题，可以做以下两种尝试：
> 
> 1. 将子目录规则设置为`{{ year }}`这种不包含`/`的形式，如果这种情况下可以移动，那么大概率是`menu.ts`中544行的`PathUtils.join`没有被成功修改为`PathUtils.joinRelative`。
> 2. 尝试自己编译最新代码，如果问题解决了，说明是Release包传错了。我在Mac上从最新源码编译的版本似乎是没问题的，需要的可以试试：[zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15036599/zotero-attanger.xpi.zip)
用了大佬的文件，可以移动了一下，之后立马就不行了

**Comment by oushiei120** [comment]
> Release中的版本确实不行，有可能是（1）Release包放错了，或者（2）编译环境问题。
> 
> 如果遇到移动失效的问题，可以做以下两种尝试：
> 
> 1. 将子目录规则设置为`{{ year }}`这种不包含`/`的形式，如果这种情况下可以移动，那么大概率是`menu.ts`中544行的`PathUtils.join`没有被成功修改为`PathUtils.joinRelative`。
> 2. 尝试自己编译最新代码，如果问题解决了，说明是Release包传错了。我在Mac上从最新源码编译的版本似乎是没问题的，需要的可以试试：[zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15036599/zotero-attanger.xpi.zip)
用了大佬的文件，可以移动了一下，之后立马就不行了

**Comment by oushiei120** [comment]
> Release中的版本确实不行，有可能是（1）Release包放错了，或者（2）编译环境问题。
> 
> 如果遇到移动失效的问题，可以做以下两种尝试：
> 
> 1. 将子目录规则设置为`{{ year }}`这种不包含`/`的形式，如果这种情况下可以移动，那么大概率是`menu.ts`中544行的`PathUtils.join`没有被成功修改为`PathUtils.joinRelative`。
> 2. 尝试自己编译最新代码，如果问题解决了，说明是Release包传错了。我在Mac上从最新源码编译的版本似乎是没问题的，需要的可以试试：[zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15036599/zotero-attanger.xpi.zip)
用了大佬的文件，可以移动了一下，之后立马就不行了

**Comment by llity** [comment]
1.1.6是正常的，新版本macOS M系列很卡，无法移动附件

**Comment by tigerjack** [comment]
I'm using 1.1.9 on Linux and I still cannot move the attachments to a proper subdirectory.

**Comment by gitkeniwo** [comment]
I'm on 1.1.9 and zotero beta.76 macOS version and ran into the same glitch as #84. Basically moving files is only possible when you leave Subfolder field blank. 

Also, it'd be helpful if there's documentation on how to build the project, as direct run of npm install raises ERESOLVE.

**Comment by c-lyu** [comment]
I just noticed that the developer invoked `PathUtils.normalize` after `PathUtils.joinRelative(destDir, subfolder)` in [this line](https://github.com/MuiseDestiny/zotero-attanger/blob/bf50a859f90e476bfc7434e7891191903ba27375/src/modules/menu.ts#L569), which breaks the cleaned path. 
Anyone who experience this issue could have a try of my build and see if the issue persists [zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15067818/zotero-attanger.xpi.zip)

**Comment by MuiseDestiny** [comment]
> I just noticed that the developer invoked `PathUtils.normalize` after `PathUtils.joinRelative(destDir, subfolder)` in [this line](https://github.com/MuiseDestiny/zotero-attanger/blob/bf50a859f90e476bfc7434e7891191903ba27375/src/modules/menu.ts#L569), which breaks the cleaned path. Anyone who experience this issue could have a try of my build and see if the issue persists [zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15067818/zotero-attanger.xpi.zip)

Thanks!!!

**Comment by DereckZhang** [comment]
> > I just noticed that the developer invoked `PathUtils.normalize` after `PathUtils.joinRelative(destDir, subfolder)` in [this line](https://github.com/MuiseDestiny/zotero-attanger/blob/bf50a859f90e476bfc7434e7891191903ba27375/src/modules/menu.ts#L569), which breaks the cleaned path. Anyone who experience this issue could have a try of my build and see if the issue persists [zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15067818/zotero-attanger.xpi.zip)
> 
> Thanks!!!
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/7668825/f271b180-7782-41a5-a5db-8b360d3bd05e)

无法移动的问题仍然没有完全解决！最新1.2.0版，如果将PDF文件直接移动到某个分类下（而不是某个条目下），此时PDF不会成为一个链接文件，而是会被移动到Zotero的官方存储，变成Stored Files

**Comment by MuiseDestiny** [comment]
> > > I just noticed that the developer invoked `PathUtils.normalize` after `PathUtils.joinRelative(destDir, subfolder)` in [this line](https://github.com/MuiseDestiny/zotero-attanger/blob/bf50a859f90e476bfc7434e7891191903ba27375/src/modules/menu.ts#L569), which breaks the cleaned path. Anyone who experience this issue could have a try of my build and see if the issue persists [zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15067818/zotero-attanger.xpi.zip)
> > 
> > 
> > Thanks!!!
> > ![image](https://private-user-images.githubusercontent.com/7668825/324668379-f271b180-7782-41a5-a5db-8b360d3bd05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDI2MTUsIm5iZiI6MTcxMzg0MjMxNSwicGF0aCI6Ii83NjY4ODI1LzMyNDY2ODM3OS1mMjcxYjE4MC03NzgyLTQxYTUtYTVkYi04YjM2MGQzYmQwNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMDMxODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VkZjIzNWVkZjRiMDgwYzdlMWMxMWViNjNkZGNhY2FkYjRjYzMxMTg0NWU5M2I0NjVmZjgzZjY2OWNlN2I1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O8DhXy8i5KZyZBtqt9fjyvIsLAyGU98rTNIBd2g5Xqc)
> 
> 无法移动的问题仍然没有完全解决！最新1.2.0版，如果将PDF文件直接移动到某个分类下（而不是某个条目下），此时PDF不会成为一个链接文件，而是会被移动到Zotero的官方存储，变成Stored Files

单独pdf不在考虑范围之内，pdf都应该有父条目

**Comment by DereckZhang** [comment]
> > > > I just noticed that the developer invoked `PathUtils.normalize` after `PathUtils.joinRelative(destDir, subfolder)` in [this line](https://github.com/MuiseDestiny/zotero-attanger/blob/bf50a859f90e476bfc7434e7891191903ba27375/src/modules/menu.ts#L569), which breaks the cleaned path. Anyone who experience this issue could have a try of my build and see if the issue persists [zotero-attanger.xpi.zip](https://github.com/MuiseDestiny/zotero-attanger/files/15067818/zotero-attanger.xpi.zip)
> > > 
> > > 
> > > Thanks!!!
> > > ![image](https://private-user-images.githubusercontent.com/7668825/324668379-f271b180-7782-41a5-a5db-8b360d3bd05e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NDI2MTUsIm5iZiI6MTcxMzg0MjMxNSwicGF0aCI6Ii83NjY4ODI1LzMyNDY2ODM3OS1mMjcxYjE4MC03NzgyLTQxYTUtYTVkYi04YjM2MGQzYmQwNWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMDMxODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VkZjIzNWVkZjRiMDgwYzdlMWMxMWViNjNkZGNhY2FkYjRjYzMxMTg0NWU5M2I0NjVmZjgzZjY2OWNlN2I1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O8DhXy8i5KZyZBtqt9fjyvIsLAyGU98rTNIBd2g5Xqc)
> > 
> > 
> > 无法移动的问题仍然没有完全解决！最新1.2.0版，如果将PDF文件直接移动到某个分类下（而不是某个条目下），此时PDF不会成为一个链接文件，而是会被移动到Zotero的官方存储，变成Stored Files
> 
> 单独pdf不在考虑范围之内，pdf都应该有父条目

学术领域确实pdf都应该有父条目，但是其他非严谨学术领域，比如复习备考这种没有参考文献管理需求时候，用zotero阅读、管理pdf也很好用（实际上我搜了很久，pdf阅读批注+笔记回链+全平台同步的主流软件只有zotero），这时候直接看pdf文件名结合collection即可
