### ISSUE TITLE
文献库的PDF附件被插件删除

### ISSUE THREAD

**Issue by ZZZZFREE** [MuiseDestiny/zotero-attanger#9]
我的zotero已经使用了坚果云webdav同步了文献库，在安装该插件后（没进行任何设置的默认情况下）多次右下角弹窗，当我查看文献时发现很多个（目测1/4库）词条的PDF附件被它删除了。
我理解这个插件可能是帮助去重或者管理附件，但它为啥在未经设置的情况下私自删除PDF附件？？（或者未经设置就擅自挪动，挪动到哪里去了？）
![image](https://github.com/MuiseDestiny/zotero-attanger/assets/101232309/38d6c33c-5d91-4c6a-bbd9-b653c63d40e7)

**Comment by ZZZZFREE** [comment]
现在可倒好，它一删除本地PDF，我坚果云再一同步，全平台的这些个PDF附件都没了

**Comment by MuiseDestiny** [comment]
自动重命名是自动的。在你没有任何配置情况下。可能进行了错误移动，这是插件问题，给你带来麻烦抱歉

**Comment by ZZZZFREE** [comment]
建议作者加个限制功能防止这类悲剧发生...PDF上面很多高亮笔记跟着一起没了

**Comment by MuiseDestiny** [comment]
是的
