### ISSUE TITLE
[Feature]：忽略Group Libraries中的附件

### ISSUE THREAD

**Issue by awwaawwa** [MuiseDestiny/zotero-attanger#91]
由于Group Libraries中不支持链接文件，所以本插件将附件移走后，无法将Zotero中的记录替换为对应链接文件。目前只能关闭Automatically move added attachments来使用本插件。如果能添加一个选项，默认忽略Group Libraries中的附件就可以解决这个问题。

> If administrators enable file sharing, group members can access and share files **in addition to references**.
> [zotero groups support](https://www.zotero.org/support/groups)

**Comment by MuiseDestiny** [comment]
如果在group则不移动吧，等下个版本
