### ISSUE TITLE
导出文件重命名优化

### ISSUE THREAD

**Issue by Miaoyeah** [MuiseDestiny/zotero-attanger#95]
希望在导出pdf重命名部分，可以优化，增加期刊名等信息，类似zotfile的{%j}，第一次发有不足还请指正，感谢感谢大佬

**Comment by MuiseDestiny** [comment]
https://www.zotero.org/support/file_renaming

这里会展示如何加入期刊信息。

题外话，目前的重命名是用的zo官方的，优化也只能等官方优化。

**Comment by Miaoyeah** [comment]
感谢大佬的回复，昨天已经看过官方，没有看过如何加入期刊，目前看来没有解决办法
| |
zjumiao2023
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年4月23日 11:37 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [MuiseDestiny/zotero-attanger] 导出文件重命名优化 (Issue #95) |

https://www.zotero.org/support/file_renaming

这里会展示如何加入期刊信息。

题外话，目前的重命名是用的zo官方的，优化也只能等官方优化。
